<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="DESKTOP-16VI708" name="com.naveentestNG.TestNGFeatures" tests="7" failures="0" timestamp="05 Jan 2018 10:48:38 GMT" time="0.044" errors="1">
  <testcase name="testCase3" time="0.000" classname="com.naveentestNG.TestNGFeatures">
    <skipped/>
  </testcase> <!-- testCase3 -->
  <testcase name="testCase7" time="0.001" classname="com.naveentestNG.TestNGFeatures">
    <skipped/>
  </testcase> <!-- testCase7 -->
  <testcase name="testCase1" time="0.034" classname="com.naveentestNG.TestNGFeatures">
    <error type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
	at com.naveentestNG.TestNGFeatures.testCase1(TestNGFeatures.java:9)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase6" time="0.002" classname="com.naveentestNG.TestNGFeatures"/>
  <testcase name="testCase4" time="0.002" classname="com.naveentestNG.TestNGFeatures"/>
  <testcase name="testCase5" time="0.000" classname="com.naveentestNG.TestNGFeatures">
    <skipped/>
  </testcase> <!-- testCase5 -->
  <testcase name="testCase2" time="0.005" classname="com.naveentestNG.TestNGFeatures"/>
</testsuite> <!-- com.naveentestNG.TestNGFeatures -->
